[ansible_targets]
node1 ansible_host=ansible-node1
node2 ansible_host=ansible-node2
node3 ansible_host=ansible-node3

[ansible_targets:vars]
ansible_connection=community.docker.docker
ansible_python_interpreter=/usr/bin/python3
